# Generated by Django 6.0.4 on 2026-05-22 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_alter_todo_options_alter_todo_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data de Vencimento"
            ),
        ),
    ]
